# ----
# Site

title: Practitioner Stories
url: "https://stephanie-k.github.io/practitioner-stories/"
baseurl: "practitioner-stories/"
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
description: Collect stories of Service Design in the public and third sectors in Scotland
author:
  name: 
  email:
  twitter: PractitionerSt1
social:
  name: Collect stories of Service Design in the public and third sectors in Scotland.
  links:
    - https://stephanie-k.github.io/practitioner-stories/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
